// migrateLogic.js — copia TODO o banco de `src` (Pool/Client já conectado) para `dstUrl` (Neon).
// Usado pelo endpoint temporário /api/admin/migrate-db, que roda DENTRO da Railway
// (assim usa a conexão interna com o banco, sem precisar da URL pública).

const { Client } = require('pg');

function tipoColuna(c) {
  const u = c.udt_name;
  const map = {
    int2: 'smallint', int4: 'integer', int8: 'bigint',
    float4: 'real', float8: 'double precision',
    bool: 'boolean', text: 'text', date: 'date',
    timestamp: 'timestamp', timestamptz: 'timestamptz',
    json: 'json', jsonb: 'jsonb', uuid: 'uuid'
  };
  if (u === 'varchar') return c.character_maximum_length ? `varchar(${c.character_maximum_length})` : 'varchar';
  if (u === 'bpchar')  return c.character_maximum_length ? `char(${c.character_maximum_length})` : 'char';
  if (u === 'numeric') return c.numeric_precision ? `numeric(${c.numeric_precision},${c.numeric_scale || 0})` : 'numeric';
  return map[u] || 'text';
}

async function tabelasDe(c) {
  const { rows } = await c.query(`
    SELECT table_name FROM information_schema.tables
    WHERE table_schema='public' AND table_type='BASE TABLE' ORDER BY table_name`);
  return rows.map(r => r.table_name);
}
async function colunasDe(c, t) {
  const { rows } = await c.query(`
    SELECT column_name, udt_name, character_maximum_length, numeric_precision, numeric_scale,
           is_nullable, column_default
    FROM information_schema.columns
    WHERE table_schema='public' AND table_name=$1 ORDER BY ordinal_position`, [t]);
  return rows;
}
async function pkDe(c, t) {
  const { rows } = await c.query(`
    SELECT a.attname FROM pg_index i
    JOIN pg_attribute a ON a.attrelid=i.indrelid AND a.attnum=ANY(i.indkey)
    WHERE i.indrelid=$1::regclass AND i.indisprimary`, [`public.${t}`]).catch(()=>({rows:[]}));
  return rows.map(r => r.attname);
}
async function uniquesDe(c, t) {
  const { rows } = await c.query(`
    SELECT con.conname, array_agg(a.attname ORDER BY array_position(con.conkey, a.attnum)) AS cols
    FROM pg_constraint con
    JOIN pg_attribute a ON a.attrelid=con.conrelid AND a.attnum=ANY(con.conkey)
    WHERE con.conrelid=$1::regclass AND con.contype='u' GROUP BY con.conname`, [`public.${t}`]).catch(()=>({rows:[]}));
  return rows.map(r => ({ cols: r.cols }));
}
const ehSerial = c => c.column_default && /nextval\(/i.test(c.column_default);
function defaultSimples(c) {
  if (!c.column_default || ehSerial(c)) return null;
  return c.column_default;
}

async function criarTabela(dst, t, cols, pk, uniques) {
  const defs = cols.map(c => {
    let d = `"${c.column_name}" ${tipoColuna(c)}`;
    if (ehSerial(c)) d += ' GENERATED BY DEFAULT AS IDENTITY';
    else { const x = defaultSimples(c); if (x) d += ` DEFAULT ${x}`; }
    if (c.is_nullable === 'NO') d += ' NOT NULL';
    return d;
  });
  if (pk.length) defs.push(`PRIMARY KEY (${pk.map(x=>`"${x}"`).join(',')})`);
  for (const u of uniques) defs.push(`UNIQUE (${u.cols.map(x=>`"${x}"`).join(',')})`);
  await dst.query(`CREATE TABLE IF NOT EXISTS "${t}" (${defs.join(', ')})`);
  const { rows: ex } = await dst.query(
    `SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1`, [t]);
  const set = new Set(ex.map(r => r.column_name));
  for (const c of cols) if (!set.has(c.column_name))
    await dst.query(`ALTER TABLE "${t}" ADD COLUMN "${c.column_name}" ${tipoColuna(c)}`);
}

async function copiarDados(src, dst, t, cols) {
  const nomes = cols.map(c => c.column_name);
  const { rows } = await src.query(`SELECT ${nomes.map(n=>`"${n}"`).join(',')} FROM "${t}"`);
  await dst.query(`TRUNCATE TABLE "${t}"`);
  if (!rows.length) return 0;
  const LOTE = 200;
  for (let i = 0; i < rows.length; i += LOTE) {
    const lote = rows.slice(i, i + LOTE);
    const params = [];
    const vals = lote.map(r => `(${nomes.map(n => { params.push(r[n]); return `$${params.length}`; }).join(',')})`);
    await dst.query(`INSERT INTO "${t}" (${nomes.map(n=>`"${n}"`).join(',')}) VALUES ${vals.join(',')}`, params);
  }
  return rows.length;
}

async function resetarSequencias(dst, t, cols) {
  for (const c of cols) if (ehSerial(c))
    await dst.query(`SELECT setval(pg_get_serial_sequence('"${t}"','${c.column_name}'),
      COALESCE((SELECT MAX("${c.column_name}") FROM "${t}"),1), true)`).catch(()=>{});
}

// src = Pool/Client já conectado (Railway). dstUrl = connection string do Neon.
async function migrarDB(src, dstUrl) {
  const dst = new Client({ connectionString: dstUrl, ssl: { rejectUnauthorized: false } });
  await dst.connect();
  try {
    const tabelas = await tabelasDe(src);
    const resumo = [];
    for (const t of tabelas) {
      const cols = await colunasDe(src, t);
      const pk = await pkDe(src, t);
      const uniques = await uniquesDe(src, t);
      await criarTabela(dst, t, cols, pk, uniques);
      const n = await copiarDados(src, dst, t, cols);
      await resetarSequencias(dst, t, cols);
      const destCount = (await dst.query(`SELECT COUNT(*)::int AS c FROM "${t}"`)).rows[0].c;
      resumo.push({ tabela: t, origem: n, destino: destCount, ok: destCount === n });
    }
    return resumo;
  } finally {
    await dst.end();
  }
}

module.exports = { migrarDB };
