// migrate.js — copia TODO o banco da Railway para o Neon.
// Uso: cria um arquivo migrate-urls.txt com 2 linhas:
//   linha 1 = connection string da RAILWAY (origem)
//   linha 2 = connection string do NEON (destino)
// Depois: node migrate.js
//
// É seguro rodar mais de uma vez (limpa o destino antes de copiar).
// No final mostra a contagem de linhas origem x destino pra conferência.

const fs = require('fs');
const { Client } = require('pg');

function lerUrls() {
  const envSrc = process.env.RAILWAY_URL, envDst = process.env.NEON_URL;
  if (envSrc && envDst) return { src: envSrc.trim(), dst: envDst.trim() };
  const txt = fs.readFileSync('migrate-urls.txt', 'utf8')
    .split('\n').map(s => s.trim()).filter(Boolean);
  if (txt.length < 2) throw new Error('migrate-urls.txt precisa ter 2 linhas (Railway e Neon)');
  return { src: txt[0], dst: txt[1] };
}

function novoClient(url) {
  return new Client({ connectionString: url, ssl: { rejectUnauthorized: false } });
}

// Mapeia o tipo do Postgres (udt_name) para um tipo de coluna válido
function tipoColuna(c) {
  const u = c.udt_name;
  const map = {
    int2: 'smallint', int4: 'integer', int8: 'bigint',
    float4: 'real', float8: 'double precision',
    bool: 'boolean', text: 'text', date: 'date',
    timestamp: 'timestamp', timestamptz: 'timestamptz',
    json: 'json', jsonb: 'jsonb', uuid: 'uuid'
  };
  if (u === 'varchar') return c.character_maximum_length ? `varchar(${c.character_maximum_length})` : 'varchar';
  if (u === 'bpchar')  return c.character_maximum_length ? `char(${c.character_maximum_length})` : 'char';
  if (u === 'numeric') {
    if (c.numeric_precision) return `numeric(${c.numeric_precision},${c.numeric_scale || 0})`;
    return 'numeric';
  }
  return map[u] || 'text';
}

async function tabelasDe(client) {
  const { rows } = await client.query(`
    SELECT table_name FROM information_schema.tables
    WHERE table_schema='public' AND table_type='BASE TABLE'
    ORDER BY table_name`);
  return rows.map(r => r.table_name);
}

async function colunasDe(client, tabela) {
  const { rows } = await client.query(`
    SELECT column_name, udt_name, data_type, character_maximum_length,
           numeric_precision, numeric_scale, is_nullable, column_default
    FROM information_schema.columns
    WHERE table_schema='public' AND table_name=$1
    ORDER BY ordinal_position`, [tabela]);
  return rows;
}

async function pkDe(client, tabela) {
  const { rows } = await client.query(`
    SELECT a.attname FROM pg_index i
    JOIN pg_attribute a ON a.attrelid=i.indrelid AND a.attnum=ANY(i.indkey)
    WHERE i.indrelid=$1::regclass AND i.indisprimary`, [`public.${tabela}`]).catch(()=>({rows:[]}));
  return rows.map(r => r.attname);
}

// Constraints UNIQUE (necessárias para os ON CONFLICT do app, ex: ranking)
async function uniquesDe(client, tabela) {
  const { rows } = await client.query(`
    SELECT con.conname, array_agg(a.attname ORDER BY array_position(con.conkey, a.attnum)) AS cols
    FROM pg_constraint con
    JOIN pg_attribute a ON a.attrelid=con.conrelid AND a.attnum=ANY(con.conkey)
    WHERE con.conrelid=$1::regclass AND con.contype='u'
    GROUP BY con.conname`, [`public.${tabela}`]).catch(()=>({rows:[]}));
  return rows.map(r => ({ nome: r.conname, cols: r.cols }));
}

function ehSerial(c) {
  return c.column_default && /nextval\(/i.test(c.column_default);
}

// Default "simples" que vale a pena recriar (literais, now(), true/false)
function defaultSimples(c) {
  if (!c.column_default) return null;
  if (ehSerial(c)) return null;
  const d = c.column_default;
  if (/nextval\(/i.test(d)) return null;
  return d; // ex: 'concluido'::text, 0, true, now(), CURRENT_TIMESTAMP
}

async function criarTabela(dst, tabela, cols, pk, uniques) {
  const defs = cols.map(c => {
    let def = `"${c.column_name}" ${tipoColuna(c)}`;
    if (ehSerial(c)) def += ' GENERATED BY DEFAULT AS IDENTITY';
    else {
      const dft = defaultSimples(c);
      if (dft) def += ` DEFAULT ${dft}`;
    }
    if (c.is_nullable === 'NO') def += ' NOT NULL';
    return def;
  });
  if (pk.length) defs.push(`PRIMARY KEY (${pk.map(x=>`"${x}"`).join(',')})`);
  for (const u of uniques) defs.push(`UNIQUE (${u.cols.map(x=>`"${x}"`).join(',')})`);
  await dst.query(`CREATE TABLE IF NOT EXISTS "${tabela}" (${defs.join(', ')})`);

  // Rede de segurança: garante que toda coluna da origem exista no destino
  const { rows: existentes } = await dst.query(
    `SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1`, [tabela]);
  const set = new Set(existentes.map(r => r.column_name));
  for (const c of cols) {
    if (!set.has(c.column_name)) {
      await dst.query(`ALTER TABLE "${tabela}" ADD COLUMN "${c.column_name}" ${tipoColuna(c)}`);
    }
  }
}

async function copiarDados(src, dst, tabela, cols) {
  const nomes = cols.map(c => c.column_name);
  const { rows } = await src.query(`SELECT ${nomes.map(n=>`"${n}"`).join(',')} FROM "${tabela}"`);
  await dst.query(`TRUNCATE TABLE "${tabela}"`);
  if (rows.length === 0) return 0;

  const LOTE = 200;
  for (let i = 0; i < rows.length; i += LOTE) {
    const lote = rows.slice(i, i + LOTE);
    const params = [];
    const valores = lote.map(r => {
      const ph = nomes.map(n => { params.push(r[n]); return `$${params.length}`; });
      return `(${ph.join(',')})`;
    });
    await dst.query(
      `INSERT INTO "${tabela}" (${nomes.map(n=>`"${n}"`).join(',')}) VALUES ${valores.join(',')}`,
      params
    );
  }
  return rows.length;
}

async function resetarSequencias(dst, tabela, cols, pk) {
  for (const c of cols) {
    if (ehSerial(c)) {
      await dst.query(`
        SELECT setval(
          pg_get_serial_sequence('"${tabela}"', '${c.column_name}'),
          COALESCE((SELECT MAX("${c.column_name}") FROM "${tabela}"), 1),
          true
        )`).catch(()=>{});
    }
  }
}

(async () => {
  const { src: srcUrl, dst: dstUrl } = lerUrls();
  const src = novoClient(srcUrl), dst = novoClient(dstUrl);
  console.log('🔌 Conectando...');
  await src.connect(); await dst.connect();
  console.log('✅ Conectado nos dois bancos.\n');

  const tabelas = await tabelasDe(src);
  console.log(`📋 ${tabelas.length} tabelas encontradas na Railway: ${tabelas.join(', ')}\n`);

  const resumo = [];
  for (const t of tabelas) {
    const cols = await colunasDe(src, t);
    const pk = await pkDe(src, t);
    const uniques = await uniquesDe(src, t);
    process.stdout.write(`→ ${t}: criando estrutura... `);
    await criarTabela(dst, t, cols, pk, uniques);
    process.stdout.write('copiando dados... ');
    const n = await copiarDados(src, dst, t, cols);
    await resetarSequencias(dst, t, cols, pk);
    // Conferência
    const destCount = (await dst.query(`SELECT COUNT(*)::int AS c FROM "${t}"`)).rows[0].c;
    const ok = destCount === n;
    console.log(`${n} linhas ${ok ? '✅' : '❌ DIVERGÊNCIA'} (destino tem ${destCount})`);
    resumo.push({ tabela: t, origem: n, destino: destCount, ok });
  }

  console.log('\n========= RESUMO =========');
  let tudoOk = true;
  for (const r of resumo) {
    console.log(`${r.ok ? '✅' : '❌'} ${r.tabela.padEnd(22)} origem=${r.origem}  destino=${r.destino}`);
    if (!r.ok) tudoOk = false;
  }
  console.log('==========================');
  console.log(tudoOk ? '\n🎉 MIGRAÇÃO COMPLETA — tudo bateu!' : '\n⚠️ ALGUMA TABELA DIVERGIU — revisar antes de usar.');

  await src.end(); await dst.end();
  process.exit(tudoOk ? 0 : 1);
})().catch(e => { console.error('\n❌ ERRO:', e.message); process.exit(1); });
